### ISSUE TITLE
IllegalStateException thrown when running on some programs

### ISSUE THREAD

**Issue by arthurrump** [creativeprogrammingatelier/atelier-PMD#22]
I get the following error when running in Atelier, for example on [this program](https://atelier.createprogramming.com/submission/RIPAep-6Q92iFmQUi7UDDw).

IllegalStateException: expressions[i].getFirstD?Type(ASTName::class.java) must not be null

This seems to be a problem in the [LongMethodRule, line 39-40](https://github.com/creativeprogrammingatelier/atelier-PMD/blob/master/src/main/kotlin/nl/utwente/processing/pmd/rules/LongMethodRule.kt#L39):

```kotlin
val methodName = expressions[i].getFirstDescendantOfType(ASTPrimaryPrefix::class.java)
                    .getFirstDescendantOfType(ASTName::class.java).image
```

@vaxaw0r Do you know what's going on here?

**Comment by vaxaw0r** [comment]
It was trying to find the Primary Prefix of a statement that was preceeded by 'this.'. Apperently when I first wrote the function I did not think about how 'this.' would change the AST. In anycase drawing block offset should not be looking at statements with assignment operators so I have filtered them out now. In any case the problem was a lacking null check but the fix should also make the method more efficient.
